In [2]:
import tensorflow as tf

In [3]:
tf.constant([[1, 2, 3], [4, 5, 6]])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [4]:
tf.constant(32)

<tf.Tensor: shape=(), dtype=int32, numpy=32>

In [5]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
t.shape

TensorShape([2, 3])

In [6]:
t.dtype

tf.int32

In [7]:
t.shape[0]

2

In [8]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]])>

In [11]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]])>

In [13]:
t+10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]])>

In [15]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]])>

In [20]:
t@tf.transpose(t)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]])>

In [21]:
tf.add(t, 3)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9]])>

In [28]:
tf.reduce_mean(tf.constant([1, 2, 3, 4, 5]))

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [15]:
import tensorflow as tf

In [16]:
t = tf.constant([1, 2, 3])

In [17]:
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [18]:
t+tf.cast(1.1, tf.int32)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [19]:
tf.add(t, tf.cast(1.2, 'int32'))

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [21]:
t[1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [39]:
t = tf.Variable(3)

In [40]:
t

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>

In [41]:
t.assign(99)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=99>

In [42]:
t

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=99>

In [43]:
t = tf.Variable([1, 2, 3])

In [44]:
t

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>

In [48]:
t.assign(2+t)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([4, 6, 8])>

In [49]:
t[0].assign(99)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([99,  6,  8])>

In [50]:
t

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([99,  6,  8])>

In [67]:
def huber_fn(y_true, y_pred):
    error = y_true - y_pred
    print(error)
    is_small_error = tf.abs(error) < 1
    print(is_small_error)
    squared_loss = tf.square(error)/2
    print(squared_loss)
    linear_loss = tf.abs(error) - 0.5
    print(linear_loss)
    return tf.where(is_small_error, squared_loss, linear_loss)

In [68]:
huber_fn(3., 2.)

1.0
tf.Tensor(False, shape=(), dtype=bool)
tf.Tensor(0.5, shape=(), dtype=float32)
tf.Tensor(0.5, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [74]:
tf.where(False, 1, 2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>